@@ -0,0 +1,36 @@
name: Sync with Upstream

on:
  schedule:
    # 每天凌晨 3:00 自动运行
    - cron: "0 3 * * *"
  workflow_dispatch: # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 检出复刻仓库代码
      - name: Checkout Fork Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 添加上游仓库作为远程仓库
      - name: Add Upstream Repository
        run: git remote add upstream https://github.com/LibreSpark/LibreTV.git

      # 拉取上游仓库最新代码
      - name: Fetch Upstream Changes
        run: git fetch upstream

      # 合并上游代码到当前分支
      - name: Merge Upstream Changes
        run: |
          git checkout main
          git merge upstream/main
      # 推送更新到复刻仓库
      - name: Push Changes to Fork
        run: git push origin main
